

export class RecFormData {

  "name" = "";
  "requisitiontypeid" = 0;
  "statusid" = 1;
  "requisitionpriorityid" = 0;
  "qualificationid" = 0;
  "jobtitle" = null;
  // "categoryid" = 0;
  "statusreasonid": null;
  location = false;
  gotowork = false;
  exclusive = false;
  offshore = false;
  exclusivedays = 1;
  zipcode = null;
  city = "";
  cityid = null;
  stateid = null;
  traveltype = null;
  remotelocationdetails: Array<RemoteLocationModel> = [];
  description = "";
  itss = false;
  clientid = null;
  clientlobid = null;
  clientlob = "";
  clientname = "";
  opportunityid = "";
  opportunityowner = "";
  hiringmanagerid = null;
  hiringmanageremail = "";
  hiringmanagerphone = "";
  hiringmanagername = null;
  vendorname = "";
  vendorid = null;
  vendoremail = "";
  vendorphone = "";
  regionid = null;
  projectname = "";
  msprojectid = null;
  practicetype = null;
  projecttypeid = 0;
  billrate = null;
  currencyid = null;
  billratetype = "";
  duedate = null;
  startdate = null;
  projectenddate = null;
  projectdurationweeks = "";
  interviewtimeslots: Array<InterviewSlotModel> = [];
  managerinterviewslots: Array<InterviewSlotModel> = [];
  salesnotes = "";
  skills: Array<any> = [];
  deliverycomments = "";
  mspstatusid = null;
  recruitername = null;
  salesrepid = null;
  insidesales = null;
  vmo = null;
  isremote = false;
  vasbulk = false;
  attachments = "";
  additionaldetails: string = null;
  isverified = false;
  jump = false;
  msprojectname = null;
  issecondarylocation = false;
  daytodayactivity = null;
  musthave = null;
  nicetohave = null;
  chatgptrecommendationid = 0;
  deliverymodelid = 0;
  circleid = null;
  communityid = null;
  isbillrateskip = false;
  isworkflowinitiated = false;
  gciid:string=null;

  clear(param?: string) {
    this.requisitiontypeid = 0;
    this.statusid = 1;
    this.qualificationid = 0;
    this.requisitionpriorityid = null;
    //    this.categoryid= 0;
    this.jobtitle = "";
    this.statusreasonid = null;
    this.location = false;
    this.gotowork = false;
    this.exclusive = false;
    this.offshore = false;
    this.exclusivedays = 1;
    this.zipcode = "";
    this.city = "";
    this.stateid = null;
    this.cityid = null;
    this.traveltype = null;
    this.remotelocationdetails = [];
    this.description = "";
    this.skills = [];
    this.itss = false;
    this.clientid = null;
    this.clientname = "";
    this.clientlobid = 0;
    this.opportunityid = "";
    this.opportunityowner = "";
    this.hiringmanagerid = null;
    this.hiringmanageremail = "";
    this.hiringmanagerphone = "";
    this.hiringmanagername = null;
    this.vendorid = null;
    this.vendorname = "";
    this.vendoremail = "";
    this.vendorphone = "";
    this.regionid = 0;
    this.projectname = "";
    this.msprojectid = null;
    this.practicetype = null;
    this.projecttypeid = null;
    this.billrate = null;
    this.currencyid = null;
    this.billratetype = null;
    this.duedate = null;
    this.startdate = null;
    this.projectenddate = null;
    this.projectdurationweeks = "";
    this.interviewtimeslots = [];
    this.managerinterviewslots = [];
    this.mspstatusid = null;
    this.salesnotes = "";
    this.deliverycomments = "";
    this.recruitername = null;
    this.salesrepid = null;
    this.insidesales = "";
    this.vmo = "";
    this.attachments = "";
    this.isremote = false;
    this.vasbulk = false;
    this.additionaldetails = null;
    this.isverified = false;
    this.jump = false;
    this.msprojectname = null;
    this.issecondarylocation = false;
    this.daytodayactivity = null;
    this.musthave = null;
    this.nicetohave = null;
    this.chatgptrecommendationid = 0;
    this.deliverymodelid = null;
    this.circleid = null;
    this.communityid = null;
    this.isbillrateskip = false;
    this.isworkflowinitiated = false;
    this.gciid = "";
  }
}


export class InterviewSlotModel {
  public interviewtypeid: string;
  public timezone: null;
  public startdatetime: string;
  public enddatetime: string;
  public description?: string;
  // public index: number;
}

export class RemoteLocationModel {
  public remotezipcode: Number;
  public remotecity: string;
  // public zipcode: Number;
}
