export const controlslist = [
    {
      "id": "1",
      "key": "Attributes",
      "Name": "Textbox",
      "label": "",
      "placeholder": "",
      "icon": "fa fa-text-width",
      "type": "textbox",
      "width": 6,
      "order": 1,
      "require": false,
      "showinlist": true,
      "addinfilter": false,
      "filterheader": "",
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": false,
      "errormsg": ""
    },
    {
      "id": "1",
      "key": "Attributes",
      "Name": "Textarea",
      "label": "",
      "placeholder": "",
      "icon": "fa fa-file-text-o",
      "type": "textarea",
      "width": 6,
      "Textlimit": 3000,
      "order": 1,
      "require": false,
      "showinlist": true,
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": false,
      "isPanel": false,
      "errormsg": "",
      "height": null
    },
    {
      "id": "1",
      "key": "Attributes",
      "Name": "Number",
      "label": "Number",
      "placeholder": "Number",
      "icon": "fa fa-sort-numeric-desc",
      "type": "number",
      "width": 6,
      "order": 2,
      "require": false,
      "showinlist": true,
      "addinfilter": false,
      "filterheader": "",
      "textalign": "left",
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": false,
      "formatoption": { "format": "number", "numbersample": "1234", "descimalplaces": "0", "separator": false, "negativenumbers": "1", "currencysample": "1,234", "cdescimalplaces": "0", "symbol": "0", "cnegativenumbers": "1" },
      "errormsg": ""
    },
    {
      "key": "Attributes",
      "Name": "Editor",
      "label": "",
      "placeholder": "",
      "icon": "fa fa-font",
      "type": "editor",
      "width": 12,
      "order": 3,
      "require": false,
      "showinlist": true,
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": false,
      "errormsg": ""
    },
    {
      "key": "Attributes",
      "Name": "Date",
      "label": "",
      "placeholder": "",
      "icon": "fa fa-calendar",
      "type": "date",
      "width": 6,
      "minDate": "1970-01-01",
      "order": 4,
      "require": false,
      "showinlist": true,
      "addinfilter": false,
      "filterheader": "",
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": false,
      "errormsg": "",
      "popupplacement": "auto"
    },
    {
      "key": "Attributes",
      "Name": "Email",
      "label": "",
      "placeholder": "",
      "icon": "fa fa-envelope-o",
      "type": "email",
      "width": 6,
      "order": 5,
      "require": false,
      "showinlist": true,
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": false,
      "errormsg": ""
    },
    {
      "key": "Attributes",
      "Name": "Phone",
      "label": "",
      "placeholder": "",
      "icon": "fa fa-phone-square",
      "type": "phonenumber",
      "width": 6,
      "order": 6,
      "require": false,
      "showinlist": true,
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": false,
      "errormsg": ""
  
    },
    {
      "key": "Attributes",
      "Name": "Password",
      "label": "",
      "placeholder": "",
      "icon": "fa fa-unlock-alt",
      "type": "password",
      "width": 6,
      "order": 7,
      "require": true,
      "showinlist": false,
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": false,
      "errormsg": ""
    },
    {
      "id": "1",
      "key": "Attributes",
      "Name": "Dropdown",
      "label": "",
      "placeholder": "",
      "icon": "fa fa-chevron-circle-down",
      "type": "dropdown",
      "width": 6,
      "allowbindingwithcontrols": false,
      "bindingwithothercontrols": [],
      "refreshfromparent": false,
      "parentcontrolkey": "",
      "apifieldforparentcontrol": "",
      "addinfilter": false,
      "filterheader": "",
      "autoselectfirstvalue": false,
      "order": 8,
      "textfield": "key",
      "valuefield": "value",
      "require": false,
      "showinlist": true,
      "haschildren": false,
      "hasdatasource": true,
      "isTableView": false,
      "apiurl": "",
      "optionlist": [],
      "storejsonnode": false,
      "errormsg": ""
    },
    {
      "key": "Attributes",
      "Name": "Autocomplete",
      "label": "",
      "placeholder": "",
      "icon": "fa fa-search",
      "type": "autocomplete",
      "width": 6,
      "order": 9,
      "textfield": "key",
      "valuefield": "value",
      "queryfield": "",
      "require": false,
      "showinlist": true,
      "haschildren": false,
      "hasdatasource": true,
      "isTableView": false,
      "apiurl": "",
      "optionlist": [],
      "storejsonnode": false,
      "errormsg": ""
    },
    {
      "key": "Attributes",
      "Name": "Checkbox",
      "label": "Display Text",
      "placeholder": "Placeholder Text",
      "icon": "fa fa-check-square-o",
      "type": "checkbox",
      "width": 6,
      "order": 10,
      "require": false,
      "Falsevalue": "",
      "Truevalue": "",
      "iscustomtext": false,
      "truetext": "",
      "falsetext": "",
      "showinlist": false,
      "addinfilter": false,
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": false,
      "errormsg": ""
  
    },
    {
      "key": "Attributes",
      "Name": "Checkbox List",
      "label": "Checkbox List",
      "placeholder": "Checkbox List",
      "showheader": false,
      "Panelheader": "",
      "icon": "fa fa-bars",
      "type": "checkboxlist",
      "direction": "verticle",
      "width": 6,
      "order": 11,
      "textfield": "key",
      "valuefield": "value",
      "Otherfield": "value",
      "require": false,
      "showinlist": false,
      "addinfilter": false,
      "filterheader": "",
      "haschildren": false,
      "hasdatasource": true,
      "isTableView": false,
      "allowother": false,
      "apiurl": "",
      "optionlist": [],
      "errormsg": ""
  
    },
    {
      "key": "Attributes",
      "Name": "Radio List",
      "label": "Radio List",
      "placeholder": "Radio List",
      "showheader": false,
      "Panelheader": "",
      "icon": "fa fa-bars",
      "type": "radio",
      "direction": "verticle",
      "width": 6,
      "allowbindingwithcontrols": false,
      "bindingwithothercontrols": [],
      "order": 11,
      "textfield": "key",
      "valuefield": "value",
      "require": false,
      "showinlist": false,
      "addinfilter": false,
      "filterheader": "",
      "haschildren": false,
      "hasdatasource": true,
      "isTableView": false,
      "allowother": false,
      "apiurl": "",
      "optionlist": [],
      "errormsg": ""
  
    },
    {
      "key": "Tablename",
      "Name": "Grid",
      "label": "",
      "icon": "fa fa-table",
      "type": "grid",
      "width": 12,
      "order": 12,
      "viewtype": "grid",
      "headerfield": "",
      "Maxrow": 5,
      "require": false,
      "showinlist": false,
      "haschildren": true,
      "hasdatasource": true,
      "isTableView": false,
      "refresh": false,
      "children": [],
      "addnewlabel": "",
      "CustomAction": []
    },
    {
      "key": "Tab",
      "Name": "Tab",
      "label": "Tab",
      "hideonedit": false,
      "Totaltab": "0",
      "icon": "fa fa-files-o",
      "type": "tab",
      "width": 12,
      "order": 13,
      "showinlist": false,
      "require": false,
      "haschildren": true,
      "hasdatasource": false,
      "IsButtonView": false,
      "IsImageButtonView": false,
      "isTableView": false,
      "IsallowChilddata": false,
      "showoptionabutton": false,
      "optionabuttonText": "Go To Next",
      "children": [],
      "IsExternalFormLoad": false
    },
    {
      "key": "Formwizard",
      "Name": "Form wizard",
      "label": "Form wizard",
      "Totalstep": "0",
      "icon": "fa fa-magic",
      "type": "formwizard",
      "width": 12,
      "order": 14,
      "showinlist": false,
      "haschildren": true,
      "hasdatasource": false,
      "isTableView": false,
      "children": [],
      "position": "bottom",
      "showdetailpanel": true,
  
  
    },
    {
      "key": "Panel",
      "Name": "Panel",
      "label": "Panel",
      "placeholder": "Panel",
      "validationfield": "",
      "Subheader": "",
      "icon": "fa fa-square-o",
      "type": "panel",
      "width": 12,
      "order": 15,
      "showinlist": false,
      "haschildren": true,
      "hasdatasource": false,
      "isTableView": false,
      "children": [],
      "column": 1,
      "showheader": true,
      "customclass": 'btn-outline-dark btn-custom-rounded',
      "ismorebutton": false,
      "popupposition": "",
      "isnotcollapsible": false
    },
    {
      "key": "Upload",
      "Name": "Upload",
      "label": "Upload",
      "placeholder": "Upload",
      "collection": "File Collection",
      "uploadtype": "single",
      "icon": "fa fa-upload",
      "type": "Upload",
      "apiurl": "",
      "width": 12,
      "order": 16,
      "require": false,
      "showinlist": false,
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": true,
      "errormsg": ""
  
    },
    {
      "key": "chart",
      "Name": "Chart",
      "label": "Chart",
      "placeholder": "Upload",
      "icon": "fa fa-line-chart",
      "type": "chart",
      "width": 12,
      "order": 18,
      "column": 1,
      "hidedata": false,
      "hidechart": false,
      "ResultApi": "",
      "ResultApiParam": [],
      "ResultDisplayField": [],
      "chartOptions": {
        "chartType": "",
        "chartName": "",
        "theme": "light",
        "curveType": "Linear"
      },
      "showinlist": false,
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": true,
      "height": null
  
    },
    {
      "key": "Card",
      "Name": "Card",
      "label": "Card",
      "placeholder": "",
      "icon": "fa fa-search-plus",
      "type": "cardgrid",
      "width": 12,
      "order": 18,
      "showinlist": false,
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": true,
      "cardtype": "Small",
      "field3Icon": "fa fa-retweet",
      "hidearrow": false,
      "actionicon": "fa fa-chevron-right",
      "field5text": "Favorite",
      "field6text": "Retweet",
      "ResultApi": "",
      "ResultApiParam": [],
      "ResultDisplayField": [],
      "PageSizeParam": "",
      "PageFromParam": "",
      "PageSize": 20,
      "PagingType": "client",
      "redirectOptions": {
        "redirecttype": "sidebar",
        "formid": "",
        "field": "",
        "condition": "0",
        "fieldvalue": 0
      },
      "ViewType": "list",
      "column": "12",
      "masonrylayout": false,
      "defaultcardimage": "",
      "showviewlink": true,
      "allowcardedit": true,
      "editcardredirecttype": "sidebar",
      "accessmodeforsidebar": "edit",
      "editcardurl": "",
      "paramforredirect": "",
      "showcardheader": false,
      "CustomAction": [],
      "actionview": "popover",
      "slideviewoption": "none",
      "slidersize": "5",
      "sidebarredirecturl": "",
      "nodataheight": null,
      "nodataimage": "",
      "nodataimagewidth": null,
      "nodatatitle": "",
      "nodatamsg": "No data available",
      "nodatabgcolor": "",
      "horizontalalignment": "",
      "iscircleimage": false,
      "imagewidth": "",
      "imageheight": "",
      "slidernavigation": false,
      "sliderpagination": false
    },
    {
      "key": "",
      "Name": "label",
      "Text": "Text",
      "label": "",
      "placeholder": "label",
      "formattype": "plain",
      "valueField": "",
      "viewtype": "namevalue",
      "hideonedit": false,
      "icon": "fa fa-eraser",
      "type": "label",
      "width": 6,
      "customClass": "",
      "order": 18,
      "showinlist": false,
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": true,
      "webicon": null,
      "mobileicon": null,
      "oneline": false,
      "horizontalalignment": "",
      "verticalalignment": ""
    },
    {
      "key": "Attributes",
      "Name": "Multi Select",
      "label": "Multi Select",
      "placeholder": "Multi Select",
      "showheader": false,
      "Panelheader": "",
      "icon": "fa fa-bars",
      "type": "multiselect",
      "width": 6,
      "order": 11,
      "textfield": "key",
      "require": false,
      "minimumselect": 0,
      "maximumselect": 50,
      "showinlist": false,
      "haschildren": false,
      "hasdatasource": true,
      "isTableView": false,
      "apiurl": "",
      "paramlist": [],
      "errormsg": ""
  
    },
    {
      "key": "Attributes",
      "Name": "Button",
      "label": "Button",
      "placeholder": "Button",
      "icon": "fa fa-bold",
      "type": "button",
      "width": 12,
      "WebIcon": "",
      "coutomClass": "",
      "order": 11,
      "require": false,
      "showinlist": false,
      "haschildren": false,
      "hasdatasource": true,
      "size": "md",
      "outline": false,
      "buttontype": "secondary",
      "actiontype": "submit",
      "redirecturl": "",
      "modelname": "",
      "apiurl": "",
      "paramlist": [],
      "successmsgicon": "fa fa-check-circle",
      "successmsgtitle": "Success",
      "successmsgtext": "Data saved.",
      "updatemsgtitle": "Updated",
      "updatemsgtext": "",
      "updatemsgicon": "fa fa-check-circle",
      "errormsgicon": "fa fa-exclamation-circle",
      "errormsgtitle": "Error",
      "errormsgtext": "Data not saved.",
      "tooltip": "",
      "tooltipplacement": "top"
  
    },
    {
      "key": "Attributes",
      "Name": "Website",
      "label": "Website",
      "placeholder": "Website",
      "icon": "fa fa-chain-broken",
      "type": "website",
      "width": 6,
      "order": 11,
      "require": false,
      "showinlist": false,
      "haschildren": false,
      "hasdatasource": true,
      "errormsg": ""
  
    },
    {
      "id": "1",
      "key": "Attributes",
      "Name": "image",
      "icon": "fa fa-picture",
      "type": "image",
      "width": 6,
      "imgwidth": 100,
      "height": 100,
      "order": 1,
      "require": false,
      "showinlist": true,
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": false,
      "imageurl": "",
      "class": ""
    },
    {
      "key": "key",
      "Name": "Rating",
      "label": "Rating",
      "type": "rating",
      "icon": "fa fa-star-half-o",
      "Noofstar": 10,
      "ShowOverallScore": true,
      "thresholdlimit": 7,
      "saveapi": "",
      "saveapiparams": [],
      "submitapi": "",
      "submitapiparams": [],
      "ratingdata": []
    },
    {
      "key": "googleplaces",
      "Name": "Google Places",
      "label": "",
      "placeholder": "",
      "icon": "fa fa-location-arrow",
      "type": "googleplaces",
      "width": 12,
      "order": 18,
      "showinlist": false,
      "StoreJsonnode": false,
      "errormsg": ""
    },
    {
      "key": "Attributes",
      "Name": "Calender",
      "label": "Calender",
      "placeholder": "Calender",
      "icon": "fa fa-calculator",
      "type": "calender",
      "width": 12,
      "order": 11,
      "require": false,
      "showinlist": false,
      "haschildren": false,
      "hasdatasource": true,
      "isTableView": true,
      "ResultApi": "",
      "ResultApiParam": [],
      "calmappingdate": "",
      "defaultcardimage": "",
      "showviewlink": true,
      "allowcardedit": true,
      "editcardredirecttype": "sidebar",
      "accessmodeforsidebar": "edit",
      "editcardurl": "",
      "paramforredirect": "",
      "showcardheader": false,
      "cardtype": "Custom",
      "ResultDisplayField": [
        {
          "DisplayName": "Title",
          "id": "41b155c2-d326-d94e-bf51-de9b9fdb35db",
          "BindingField": "",
          "isEmail": false,
          "isIcon": false,
          "redirecturl": false,
          "redirectparam": false
        },
        {
          "DisplayName": "Description",
          "id": "aa3bb191-977e-5700-3d9d-23854b04af24",
          "BindingField": "",
          "isEmail": false,
          "isIcon": false,
          "redirecturl": false,
          "redirectparam": false
        },
        {
          "DisplayName": "PictureUrl",
          "id": "4c170c38-4f78-9347-985d-27ab6b26282c",
          "BindingField": "",
          "isEmail": false,
          "isIcon": false,
          "redirecturl": false,
          "redirectparam": false
        }
      ],
      "CustomAction": [],
      "actionview": "popover"
    },
    {
      "key": "kanban",
      "Name": "kanban",
      "label": "",
      "placeholder": "",
      "icon": "fa fa-window-maximize",
      "type": "kanban",
      "width": 12,
      "order": 18,
      "addformid": "",
      "status": [],
      "updateapi": "",
      "updateapiparam": [],
      "ResultApi": "",
      "ResultApiParam": [],
      "groupingfield": "",
      "statusfield": "",
      "defaultcardimage": "",
      "showviewlink": true,
      "allowcardedit": true,
      "editcardredirecttype": "sidebar",
      "accessmodeforsidebar": "edit",
      "editcardurl": "",
      "paramforredirect": "",
      "showcardheader": false,
      "cardtype": "Custom",
      "ResultDisplayField": [
        {
          "DisplayName": "Title",
          "id": "41b155c2-d326-d94e-bf51-de9b9fdb35db",
          "BindingField": "",
          "fieldtype": "none",
          "redirecturl": false,
          "redirectparam": false
        },
        {
          "DisplayName": "Description",
          "id": "aa3bb191-977e-5700-3d9d-23854b04af24",
          "BindingField": "",
          "fieldtype": "none",
          "redirecturl": false,
          "redirectparam": false
        },
        {
          "DisplayName": "PictureUrl",
          "id": "4c170c38-4f78-9347-985d-27ab6b26282c",
          "BindingField": "",
          "fieldtype": "none",
          "redirecturl": false,
          "redirectparam": false
        }
      ],
      "CustomAction": [],
      "actionview": "popover",
      "nodataheight": null,
      "nodataimage": "",
      "nodataimagewidth": null,
      "nodatatitle": "",
      "nodatamsg": "No data available",
      "nodatabgcolor": ""
    },
  
    {
      "key": "key",
      "Name": "Timeline",
      "label": "Timeline",
      "type": "timeline",
      "icon": "fa fa-clock-o",
      "width": 12,
      "updateapi": "",
      "updateapiparam": [],
      "ResultApi": "",
      "ResultApiParam": [],
      "timelinedate": "",
      "docuploadapi": "",
      "Userid": "",
      "documemtid": "",
      "timelineid": "",
      "createby": "",
      "respondby": "",
      "ResultDisplayField": [
        {
          "DisplayName": "Title",
          "id": "41b155c2-d326-d94e-bf51-de9b9fdb35db",
          "BindingField": ""
        },
        {
          "DisplayName": "Description",
          "id": "aa3bb191-977e-5700-3d9d-23854b04af24",
          "BindingField": ""
        }
      ]
    },
    {
      "key": "Attributes",
      "Name": "Dropdown 2",
      "label": "",
      "placeholder": "",
      "icon": "fa fa-chevron-circle-down",
      "type": "dropdown2",
      "width": 6,
      "order": 4,
      "require": false,
      "showinlist": true,
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": false,
      "allowbindingwithcontrols": false,
      "bindingwithothercontrols": [],
      "refreshfromparent": false,
      "parentcontrolkey": "",
      "apifieldforparentcontrol": "",
      "addinfilter": false,
      "filterheader": "",
      "autoselectfirstvalue": false,
      "textfield": "key",
      "valuefield": "value",
      "ResultApi": "",
      "ResultApiParam": [],
      "optionlist": [],
      "storejsonnode": false,
      "selectiontype": "single",
      "defaulttext": "Select",
      "selectalltext": "Select All",
      "unselectalltext": "UnSelect All",
      "enablesearchfilter": false,
      "pullRight": false,
      "selectionLimit": null,
      "closeOnSelect": true,
      "maxHeight": "400px",
      "isLazyLoad": false,
      "from": "from",
      "search": "",
      "dynamictitlemaxitems": 0,
      "showcheckall": false,
      "showuncheckall": false,
      "outputtype": "text",
      "errormsg": "",
      "customoption": false
    },
    {
      "key": "map",
      "Name": "Map",
      "label": "",
      "placeholder": "",
      "icon": "fa fa-globe",
      "type": "map",
      "width": 12,
      "order": 18,
      "mapheight": "800px",
      "markerIconUrl": "",
      "markerlabel": "",
      "markertitle": "",
      "markerClickable": true,
      "markerDraggable": false,
      "openInfoWindow": true,
      "markervisible": true,
      "ResultApi": "",
      "ResultApiParam": [],
      "latitudefield": "",
      "longitudefield": "",
      "datanode": "",
      "defaultcardimage": "",
      "cardtype": "Custom",
      "ResultDisplayField": [
        {
          "DisplayName": "Title",
          "id": "41b155c2-d326-d94e-bf51-de9b9fdb35db",
          "BindingField": "",
          "fieldtype": "none",
          "redirecturl": false,
          "redirectparam": false
        },
        {
          "DisplayName": "Description",
          "id": "aa3bb191-977e-5700-3d9d-23854b04af24",
          "BindingField": "",
          "fieldtype": "none",
          "redirecturl": false,
          "redirectparam": false
        },
        {
          "DisplayName": "PictureUrl",
          "id": "4c170c38-4f78-9347-985d-27ab6b26282c",
          "BindingField": "",
          "fieldtype": "none",
          "redirecturl": false,
          "redirectparam": false
        }
      ],
      "options": []
    },
    {
      "id": "78559d67-dd78-4eff-9a7b-588e45d7d413",
      "key": "Attributes",
      "Name": "Statistic Card",
      "icon": "fa fa-id-card",
      "type": "statisticcard",
      "width": 3,
      "order": 50,
      "cardType": "",
      "bgColor": "",
      "bgImage": "",
      "fontColor": "",
      "cardIcon": "",
      "cardIconColor": "",
      "cardButton": "",
      "cardButtonColor": "",
      "CardButtonUrl": "",
      "title": "",
      "subTitle": "",
      "Api": "",
      "ApiParam": [],
      "value": "",
      "subValue": "",
      "dataType": "",
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": false,
      "ResultDisplayField": [],
      "showchart": false,
      "chartOptions": {
        "chartType": "",
        "chartName": "",
        "theme": "light",
        "curveType": "Linear",
        "width": 100,
        "height": 50,
        "view": [
          100,
          50
        ],
      },
      "ResultApi": "",
      "ResultApiParam": []
  
    },
    {
      "id": "1",
      "key": "Attributes",
      "Name": "Expression",
      "label": "",
      "placeholder": "",
      "icon": "fa fa-calculator",
      "type": "expression",
      "width": 6,
      "order": 1,
      "require": false,
      "showinlist": true,
      "addinfilter": false,
      "filterheader": "",
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": false,
      "formattype": "P",
      "hidden": false,
      "operation": []
    },
    {
      "id": "1",
      "key": "Attributes",
      "Name": "Group Expression",
      "label": "",
      "placeholder": "",
      "icon": "fa fa-calculator",
      "type": "groupcalc",
      "width": 6,
      "Textlimit": 3000,
      "order": 1,
      "require": false,
      "showinlist": true,
      "haschildren": false,
      "isTableView": false,
      "hasdatasource": false,
      "formattype": "P",
      "hidden": false,
      "expression": {}
    },
    {
      "key": "grid",
      "Name": "Advance Grid",
      "label": "Advance Grid",
      "icon": "fa fa-window-maximize",
      "type": "advancegrid",
      "width": 12,
      "showselectcolumn": true,
      "showeditlink": true,
      "showupdatelink": true,
      "showdeletelink": true,
      "showexportlink": true,
      "showemaillink": true,
      "showemanagecolumn": true,
      "showefreezecolumn": true,
      "primarykey": "",
      "editformid": "",
      "deleteapi": "",
      "deleteapiparam": [],
      "updateapi": "",
      "updateapiparam": [],
      "ResultApi": "",
      "emailformid": "",
      "emailfieldDestination": "",
      "emailfieldSource": "",
      "PagingType": "client",
      "PageSize": "10",
      "PageSizeParam": "",
      "ResultApiParam": [],
      "allowcardedit": false,
      "editcardredirecttype": "sidebar",
      "accessmodeforsidebar": "edit",
      "editcardurl": "",
      "paramforredirect": "",
      "ResultDisplayField": [],
      "nodataheight": null,
      "nodataimage": "",
      "nodataimagewidth": null,
      "nodatatitle": "",
      "nodatamsg": "No data available",
      "nodatabgcolor": "",
      "rawquery": ""
    },
    {
      "key": "Rules",
      "Name": "Rules Container",
      "label": "",
      "icon": "fa fa-tachometer",
      "type": "rulescontainer",
      "width": 12,
      "order": 12,
      "hasdatasource": false,
      "haschildren": true,
      "children": [],
      "CustomAction": [],
      "actionview": "popover"
    },
    {
      "key": "Attributes",
      "Name": "Progressbar",
      "icon": "fa fa-spinner",
      "type": "progressbar",
      "order": 1,
      "optionlist": [],
      "label": "",
      "width": null,
      "progressbartype": "",
      "barcolor": "",
      "striped": false,
      "animation": false,
      "outerstrokewidth": null,
      "outerstrokecolor": "",
      "outerstrokelinecap": "",
      "animationduration": null,
      "clockwise": false,
      "space": null,
      "showTitle": false,
      "titlecolor": "",
      "titlefontsize": "",
      "animatetitle": false,
      "showsubtitle": false,
      "subtitle": "",
      "subtitlecolor": "",
      "subtitlefontsize": "",
      "animatesubtitle": false,
      "showunits": false,
      "units": "",
      "unitsfontsize": "",
      "unitscolor": "",
      "showbackground": false,
      "backgroundstroke": "",
      "backgroundStrokeWidth": null,
      "backgroundPadding": null,
      "backgroundColor": "",
      "backgroundOpacity": null,
      "showInnerstroke": false,
      "innerstrokewidth": null,
      "innerstrokecolor": "",
      "tofixed": null,
      "renderonclick": false,
      "class": "",
      "barwidth": null,
      "barheight": null
    },
    {
      "key": "nested",
      "Name": "Nested",
      "label": "Nested",
      "icon": "fa fa-plus",
      "type": "nested",
      "width": 12,
      "order": 15,
      "showinlist": false,
      "haschildren": true,
      "hasdatasource": false,
      "isTableView": false,
      "children": []
    },
  ]
  export const controls = {
    "General": [
      {
        "id": "1",
        "key": "Attributes",
        "Name": "Textbox",
        "label": "",
        "placeholder": "",
        "icon": "fa fa-text-width",
        "type": "textbox",
        "width": 6,
        "order": 1,
        "require": false,
        "showinlist": true,
        "addinfilter": false,
        "filterheader": "",
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": false,
        "help": "",
        "helpdirection": "top"
      },
      {
        "id": "1",
        "key": "Attributes",
        "Name": "Textarea",
        "label": "",
        "placeholder": "",
        "icon": "fa fa-file-text-o",
        "type": "textarea",
        "width": 6,
        "Textlimit": 3000,
        "order": 1,
        "require": false,
        "showinlist": true,
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": false,
        "help": "",
        "helpdirection": "top"
      },
      {
        "id": "1",
        "key": "Attributes",
        "Name": "Number",
        "label": "Number",
        "placeholder": "Number",
        "icon": "fa fa-sort-numeric-desc",
        "type": "number",
        "width": 6,
        "order": 2,
        "require": false,
        "max": null,
        "min": null,
        "showinlist": true,
        "addinfilter": false,
        "filterheader": "",
        "textalign": "left",
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": false,
        "formatoption": {
          "format": "number",
          "numbersample": "1234",
          "descimalplaces": "0",
          "separator": false,
          "negativenumbers": "1",
          "currencysample": "1,234",
          "cdescimalplaces": "0",
          "symbol": "0",
          "cnegativenumbers": "1"
        },
        "help": "",
        "helpdirection": "top"
      },
      {
        "key": "Attributes",
        "Name": "Editor",
        "label": "",
        "placeholder": "",
        "icon": "fa fa-font",
        "type": "editor",
        "width": 12,
        "order": 3,
        "require": false,
        "showinlist": true,
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": false,
        "help": "",
        "helpdirection": "top"
      },
      {
        "key": "Attributes",
        "Name": "Date",
        "label": "",
        "placeholder": "",
        "icon": "fa fa-calendar",
        "type": "date",
        "width": 6,
        "minDate": "1970-01-01",
        "order": 4,
        "require": false,
        "showinlist": true,
        "addinfilter": false,
        "filterheader": "",
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": false,
        "help": "",
        "helpdirection": "top"
      },
      {
        "key": "Attributes",
        "Name": "Email",
        "label": "",
        "placeholder": "",
        "icon": "fa fa-envelope-o",
        "type": "email",
        "width": 6,
        "order": 5,
        "require": false,
        "showinlist": true,
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": false,
        "help": "",
        "helpdirection": "top"
      },
      {
        "key": "Attributes",
        "Name": "Phone",
        "label": "",
        "placeholder": "",
        "icon": "fa fa-phone-square",
        "type": "phonenumber",
        "width": 6,
        "order": 6,
        "require": false,
        "showinlist": true,
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": false,
        "help": "",
        "helpdirection": "top"
      },
      {
        "key": "Attributes",
        "Name": "Password",
        "label": "",
        "placeholder": "",
        "icon": "fa fa-unlock-alt",
        "type": "password",
        "width": 6,
        "order": 7,
        "require": true,
        "showinlist": false,
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": false,
        "help": "",
        "helpdirection": "top"
      },
      {
        "key": "Attributes",
        "Name": "Checkbox",
        "label": "Display Text",
        "placeholder": "Placeholder Text",
        "icon": "fa fa-check-square-o",
        "type": "checkbox",
        "width": 6,
        "order": 10,
        "require": false,
        "Falsevalue": "",
        "Truevalue": "",
        "iscustomtext": false,
        "truetext": "",
        "falsetext": "",
        "showinlist": false,
        "addinfilter": false,
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": false,
        "hideswitchtext": false,
        "help": "",
        "helpdirection": "top"
      },
      {
        "key": "Upload",
        "Name": "File Upload",
        "label": "File Upload",
        "placeholder": "File Upload",
        "collection": "File Collection",
        "uploadtype": "single",
        "icon": "fa fa-upload",
        "type": "Upload",
        "apiurl": "",
        "width": 12,
        "order": 16,
        "require": false,
        "showinlist": false,
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": true,
        "help": "",
        "helpdirection": "top"
      },
      {
        "key": "",
        "Name": "label",
        "Text": "Text",
        "label": "",
        "placeholder": "label",
        "formattype": "plain",
        "valueField": "",
        "viewtype": "namevalue",
        "hideonedit": false,
        "icon": "fa fa-eraser",
        "type": "label",
        "width": 6,
        "order": 18,
        "showinlist": false,
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": true
      },
      {
        "key": "Attributes",
        "Name": "Button",
        "label": "Button",
        "placeholder": "Button",
        "icon": "fa fa-bold",
        "type": "button",
        "width": 6,
        "order": 11,
        "require": false,
        "showinlist": false,
        "haschildren": false,
        "hasdatasource": true,
        "size": "sm",
        "outline": false,
        "buttontype": "flat",
        "actiontype": "submit",
        "notificationformid": "",
        "redirecturl": "",
        "modelname": "",
        "apiurl": "",
        "paramlist": [],
        "updatemsgtitle": "Updated",
        "updatemsgtext": "",
        "updatemsgicon": "fa fa-check-circle"
      },
      {
        "id": "1",
        "key": "Attributes",
        "Name": "Bookmark",
        "label": "",
        "placeholder": "",
        "icon": "fa fa-bookmark",
        "type": "bookmark",
        "titlemodel": "",
        "subtitlemodel": "",
        "iconcss": "",
        "WebIcon": "",
        "size": "",
        "buttontype": "",
        "coutomClass": "",
        "width": 6,
        "order": 1,
        "showinlist": true,
        "haschildren": false,
        "hasdatasource": false
      },
      {
        "key": "Attributes",
        "Name": "Website",
        "label": "Website",
        "placeholder": "Website",
        "icon": "fa fa-chain-broken",
        "type": "website",
        "width": 6,
        "order": 11,
        "require": false,
        "showinlist": false,
        "haschildren": false,
        "hasdatasource": true,
        "help": "",
        "helpdirection": "top"
      },
      {
        "id": "1",
        "key": "Attributes",
        "Name": "image",
        "icon": "fa fa-file-image-o",
        "type": "image",
        "width": 6,
        "imgwidth": "100",
        "height": "100",
        "order": 1,
        "require": false,
        "showinlist": true,
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": false,
        "imageurl": "",
        "class": "",
        "isbackgroundimage": false
      },
      {
        "key": "key",
        "Name": "Rating",
        "label": "Rating",
        "type": "rating",
        "icon": "fa fa-star-half-o",
        "Noofstar": 10,
        "ShowOverallScore": true,
        "thresholdlimit": 7,
        "saveapi": "",
        "saveapiparams": [],
        "submitapi": "",
        "submitapiparams": [],
        "ratingdata": []
      },
      {
        "key": "googleplaces",
        "Name": "Google Places",
        "label": "",
        "placeholder": "",
        "icon": "fa fa-location-arrow",
        "type": "googleplaces",
        "width": 12,
        "order": 18,
        "showinlist": false,
        "StoreJsonnode": false,
        "help": "",
        "helpdirection": "top"
      },
      {
        "id": "1",
        "key": "Attributes",
        "Name": "Expression",
        "label": "",
        "placeholder": "",
        "icon": "fa fa-calculator",
        "type": "expression",
        "width": 6,
        "order": 1,
        "require": false,
        "showinlist": true,
        "addinfilter": false,
        "filterheader": "",
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": false,
        "formattype": "P",
        "hidden": false,
        "operation": []
      },
      {
        "id": "1",
        "key": "Attributes",
        "Name": "Group Expression",
        "label": "",
        "placeholder": "",
        "icon": "fa fa-calculator",
        "type": "groupcalc",
        "width": 6,
        "Textlimit": 3000,
        "order": 1,
        "require": false,
        "showinlist": true,
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": false,
        "formattype": "P",
        "hidden": false,
        "expression": {}
      },
      {
        "key": "hidden",
        "Name": "Hidden",
        "label": "",
        "icon": "fa fa-tachometer",
        "type": "hidden",
        "width": 12,
        "order": 12,
        "value": "",
        "sourcetype": ""
      },
      {
        "id": "1",
        "key": "Attributes",
        "Name": "iFrame",
        "icon": "fa fa-window-maximize",
        "type": "iframe",
        "width": 12,
        "height": "75vh",
        "order": 1,
        "require": false,
        "showinlist": true,
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": false,
        "src": ""
      }
  
    ],
    "Databinding": [
      {
        "key": "Attributes",
        "Name": "Autocomplete",
        "label": "",
        "placeholder": "",
        "icon": "fa fa-search",
        "type": "autocomplete",
        "width": 6,
        "order": 9,
        "textfield": "key",
        "valuefield": "value",
        "queryfield": "",
        "require": false,
        "showinlist": true,
        "haschildren": false,
        "hasdatasource": true,
        "isTableView": false,
        "apiurl": "",
        "optionlist": [],
        "storejsonnode": false,
        "help": "",
        "helpdirection": "top"
      },
      {
        "key": "Attributes",
        "Name": "Checkbox List",
        "label": "Checkbox List",
        "placeholder": "Checkbox List",
        "showheader": false,
        "Panelheader": "",
        "icon": "fa fa-bars",
        "type": "checkboxlist",
        "direction": "verticle",
        "width": 6,
        "order": 11,
        "textfield": "key",
        "valuefield": "value",
        "Otherfield": "value",
        "require": false,
        "showinlist": false,
        "addinfilter": false,
        "filterheader": "",
        "haschildren": false,
        "hasdatasource": true,
        "isTableView": false,
        "allowother": false,
        "apiurl": "",
        "optionlist": [],
        "help": "",
        "helpdirection": "top"
      },
      {
        "key": "Attributes",
        "Name": "Radio List",
        "label": "Radio List",
        "placeholder": "Radio List",
        "showheader": false,
        "Panelheader": "",
        "icon": "fa fa-bars",
        "type": "radio",
        "direction": "verticle",
        "width": 6,
        "allowbindingwithcontrols": false,
        "bindingwithothercontrols": [],
        "order": 11,
        "textfield": "key",
        "valuefield": "value",
        "require": false,
        "showinlist": false,
        "addinfilter": false,
        "filterheader": "",
        "haschildren": false,
        "hasdatasource": true,
        "isTableView": false,
        "allowother": false,
        "apiurl": "",
        "optionlist": [],
        "help": "",
        "helpdirection": "top"
      },
      {
        "key": "Attributes",
        "Name": "Multi Select",
        "label": "Multi Select",
        "placeholder": "Multi Select",
        "showheader": false,
        "Panelheader": "",
        "icon": "fa fa-bars",
        "type": "multiselect",
        "width": 6,
        "order": 11,
        "textfield": "key",
        "require": false,
        "showinlist": false,
        "haschildren": false,
        "hasdatasource": true,
        "isTableView": false,
        "apiurl": "",
        "paramlist": [],
        "help": "",
        "helpdirection": "top"
      },
      {
        "key": "Attributes",
        "Name": "Dropdown 2",
        "label": "",
        "placeholder": "",
        "icon": "fa fa-chevron-circle-down",
        "type": "dropdown2",
        "width": 6,
        "order": 4,
        "require": false,
        "showinlist": true,
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": false,
        "allowbindingwithcontrols": false,
        "bindingwithothercontrols": [],
        "refreshfromparent": false,
        "parentcontrolkey": "",
        "apifieldforparentcontrol": "",
        "addinfilter": false,
        "filterheader": "",
        "autoselectfirstvalue": false,
        "textfield": "key",
        "valuefield": "value",
        "ResultApi": "",
        "ResultApiParam": [],
        "optionlist": [],
        "storejsonnode": false,
        "selectiontype": "single",
        "defaulttext": "Select",
        "selectalltext": "Select All",
        "unselectalltext": "UnSelect All",
        "enablesearchfilter": false,
        "pullRight": false,
        "selectionLimit": null,
        "closeOnSelect": true,
        "maxHeight": "400px",
        "isLazyLoad": false,
        "from": "from",
        "search": "",
        "dynamictitlemaxitems": 0,
        "showcheckall": false,
        "showuncheckall": false,
        "customoption": false,
        "help": "",
        "helpdirection": "top"
      }
    ],
    "Container": [
      {
        "key": "Tablename",
        "Name": "Grid",
        "label": "",
        "icon": "fa fa-table",
        "type": "grid",
        "width": 12,
        "order": 12,
        "viewtype": "grid",
        "headerfield": "",
        "Maxrow": 5,
        "require": false,
        "showinlist": false,
        "haschildren": true,
        "hasdatasource": true,
        "isTableView": false,
        "refresh": false,
        "children": [],
        "addnewlabel": "",
        "CustomAction": []
      },
      {
        "key": "Tab",
        "Name": "Tab",
        "label": "Tab",
        "hideonedit": false,
        "Totaltab": "0",
        "icon": "fa fa-files-o",
        "type": "tab",
        "width": 12,
        "order": 13,
        "showinlist": false,
        "require": false,
        "haschildren": true,
        "hasdatasource": false,
        "IsButtonView": false,
        "IsImageButtonView": false,
        "isTableView": false,
        "IsallowChilddata": false,
        "showoptionabutton": false,
        "optionabuttonText": "Go To Next",
        "children": [],
        "IsExternalFormLoad": false
      },
      {
        "key": "Formwizard",
        "Name": "Form wizard",
        "label": "Form wizard",
        "Totalstep": "0",
        "icon": "fa fa-magic",
        "type": "formwizard",
        "width": 12,
        "order": 14,
        "coutomClass": "btn-sm",
        "buttontype": "btn-outline-primary",
        "showinlist": false,
        "haschildren": true,
        "hasdatasource": false,
        "isTableView": false,
        "children": [],
        "position": "bottom",
        "showdetailpanel": true
      },
      {
        "key": "Panel",
        "Name": "Panel",
        "label": "Panel",
        "placeholder": "Panel",
        "validationfield": "",
        "Subheader": "",
        "icon": "fa fa-square-o",
        "type": "panel",
        "width": 12,
        "order": 15,
        "showinlist": false,
        "haschildren": true,
        "hasdatasource": false,
        "isTableView": false,
        "children": [],
        "column": 1,
        "showheader": true
      },
      {
        "key": "Rules",
        "Name": "Rules Container",
        "label": "",
        "icon": "fa fa-tachometer",
        "type": "rulescontainer",
        "width": 12,
        "order": 12,
        "hasdatasource": false,
        "haschildren": true,
        "children": [],
        "CustomAction": [],
        "actionview": "popover"
      },
      {
        "key": "nested",
        "Name": "Nested",
        "label": "Nested",
        "showheader": true,
        "icon": "fa fa-plus",
        "type": "nested",
        "width": 12,
        "order": 15,
        "showinlist": false,
        "haschildren": true,
        "hasdatasource": false,
        "isTableView": false,
        "children": [],
        "nodataheight": null,
        "nodataimage": "",
        "nodataimagewidth": null,
        "nodatatitle": "",
        "nodatamsg": "No data available",
        "nodatabgcolor": "",
      },
    ],
    "Dataview": [
      {
        "key": "Card",
        "Name": "Card",
        "label": "Card",
        "placeholder": "",
        "icon": "fa fa-search-plus",
        "type": "cardgrid",
        "width": 12,
        "order": 18,
        "showinlist": false,
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": true,
        "cardtype": "Small",
        "field3Icon": "fa fa-retweet",
        "hidearrow": false,
        "actionicon": "fa fa-chevron-right",
        "field5text": "Favorite",
        "field6text": "Retweet",
        "ResultApi": "",
        "ResultApiParam": [],
        "ResultDisplayField": [],
        "PageSizeParam": "",
        "PageFromParam": "",
        "PageSize": 20,
        "PagingType": "client",
        "redirectOptions": {
          "redirecttype": "sidebar",
          "formid": "",
          "field": "",
          "condition": "0",
          "fieldvalue": 0
        },
        "ViewType": "list",
        "column": "12",
        "masonrylayout": false,
        "defaultcardimage": "",
        "showviewlink": true,
        "allowcardedit": true,
        "editcardredirecttype": "sidebar",
        "accessmodeforsidebar": "edit",
        "editcardurl": "",
        "paramforredirect": "",
        "showcardheader": false,
        "CustomAction": [],
        "actionview": "popover",
        "slideviewoption": "none",
        "slidersize": "5",
        "sidebarredirecturl": "",
        "iscircleimage": false,
        "imagewidth": "",
        "imageheight": "",
        "slidernavigation": false,
        "sliderpagination": false
      },
      {
        "key": "Attributes",
        "Name": "Calender",
        "label": "Calender",
        "placeholder": "Calender",
        "icon": "fa fa-calculator",
        "type": "calender",
        "width": 12,
        "order": 11,
        "require": false,
        "showinlist": false,
        "haschildren": false,
        "hasdatasource": true,
        "isTableView": true,
        "ResultApi": "",
        "ResultApiParam": [],
        "calmappingdate": "",
        "defaultcardimage": "",
        "showviewlink": true,
        "allowcardedit": true,
        "editcardredirecttype": "sidebar",
        "accessmodeforsidebar": "edit",
        "editcardurl": "",
        "paramforredirect": "",
        "showcardheader": false,
        "cardtype": "Custom",
        "ResultDisplayField": [
          {
            "DisplayName": "Title",
            "id": "41b155c2-d326-d94e-bf51-de9b9fdb35db",
            "BindingField": "",
            "isEmail": false,
            "isIcon": false,
            "redirecturl": false,
            "redirectparam": false
          },
          {
            "DisplayName": "Description",
            "id": "aa3bb191-977e-5700-3d9d-23854b04af24",
            "BindingField": "",
            "isEmail": false,
            "isIcon": false,
            "redirecturl": false,
            "redirectparam": false
          },
          {
            "DisplayName": "PictureUrl",
            "id": "4c170c38-4f78-9347-985d-27ab6b26282c",
            "BindingField": "",
            "isEmail": false,
            "isIcon": false,
            "redirecturl": false,
            "redirectparam": false
          }
        ],
        "CustomAction": [],
        "actionview": "popover"
      },
      {
        "key": "kanban",
        "Name": "kanban",
        "label": "",
        "placeholder": "",
        "icon": "fa fa-window-maximize",
        "type": "kanban",
        "width": 12,
        "order": 18,
        "addformid": "",
        "status": [],
        "updateapi": "",
        "updateapiparam": [],
        "ResultApi": "",
        "ResultApiParam": [],
        "groupingfield": "",
        "statusfield": "",
        "defaultcardimage": "",
        "showviewlink": true,
        "allowcardedit": true,
        "editcardredirecttype": "sidebar",
        "accessmodeforsidebar": "edit",
        "editcardurl": "",
        "paramforredirect": "",
        "showcardheader": false,
        "cardtype": "Custom",
        "ResultDisplayField": [
          {
            "DisplayName": "Title",
            "id": "41b155c2-d326-d94e-bf51-de9b9fdb35db",
            "BindingField": "",
            "fieldtype": "none",
            "redirecturl": false,
            "redirectparam": false
          },
          {
            "DisplayName": "Description",
            "id": "aa3bb191-977e-5700-3d9d-23854b04af24",
            "BindingField": "",
            "fieldtype": "none",
            "redirecturl": false,
            "redirectparam": false
          },
          {
            "DisplayName": "PictureUrl",
            "id": "4c170c38-4f78-9347-985d-27ab6b26282c",
            "BindingField": "",
            "fieldtype": "none",
            "redirecturl": false,
            "redirectparam": false
          }
        ],
        "CustomAction": [],
        "actionview": "popover"
      },
      {
        "key": "key",
        "Name": "Timeline",
        "label": "Timeline",
        "type": "timeline",
        "icon": "fa fa-clock-o",
        "width": 12,
        "updateapi": "",
        "updateapiparam": [],
        "ResultApi": "",
        "ResultApiParam": [],
        "timelinedate": "",
        "docuploadapi": "",
        "Userid": "",
        "documemtid": "",
        "timelineid": "",
        "createby": "",
        "respondby": "",
        "ResultDisplayField": [
          {
            "DisplayName": "Title",
            "id": "41b155c2-d326-d94e-bf51-de9b9fdb35db",
            "BindingField": ""
          },
          {
            "DisplayName": "Description",
            "id": "aa3bb191-977e-5700-3d9d-23854b04af24",
            "BindingField": ""
          }
        ]
      },
      {
        "key": "chart",
        "Name": "Chart",
        "label": "Chart",
        "placeholder": "Upload",
        "icon": "fa fa-line-chart",
        "type": "chart",
        "width": 12,
        "order": 18,
        "column": 1,
        "hidedata": false,
        "hidechart": false,
        "ResultApi": "",
        "ResultApiParam": [],
        "ResultDisplayField": [],
        "chartOptions": {
          "chartType": "",
          "chartName": "",
          "theme": "light",
          "curveType": "Linear"
        },
        "showinlist": false,
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": true
      },
      {
        "key": "map",
        "Name": "Map",
        "label": "",
        "placeholder": "",
        "icon": "fa fa-globe",
        "type": "map",
        "width": 12,
        "order": 18,
        "mapheight": "800px",
        "markerIconUrl": "",
        "markerlabel": "",
        "markertitle": "",
        "markerClickable": true,
        "markerDraggable": false,
        "openInfoWindow": true,
        "markervisible": true,
        "ResultApi": "",
        "ResultApiParam": [],
        "latitudefield": "",
        "longitudefield": "",
        "datanode": "",
        "defaultcardimage": "",
        "cardtype": "Custom",
        "ResultDisplayField": [
          {
            "DisplayName": "Title",
            "id": "41b155c2-d326-d94e-bf51-de9b9fdb35db",
            "BindingField": "",
            "fieldtype": "none",
            "redirecturl": false,
            "redirectparam": false
          },
          {
            "DisplayName": "Description",
            "id": "aa3bb191-977e-5700-3d9d-23854b04af24",
            "BindingField": "",
            "fieldtype": "none",
            "redirecturl": false,
            "redirectparam": false
          },
          {
            "DisplayName": "PictureUrl",
            "id": "4c170c38-4f78-9347-985d-27ab6b26282c",
            "BindingField": "",
            "fieldtype": "none",
            "redirecturl": false,
            "redirectparam": false
          }
        ],
        "options": []
      },
      {
        "id": "78559d67-dd78-4eff-9a7b-588e45d7d413",
        "key": "Attributes",
        "Name": "Statistic Card",
        "icon": "fa fa-id-card",
        "type": "statisticcard",
        "width": 3,
        "order": 50,
        "cardType": "",
        "bgColor": "",
        "bgImage": "",
        "fontColor": "",
        "cardIcon": "",
        "cardIconColor": "",
        "cardButton": "",
        "cardButtonColor": "",
        "CardButtonUrl": "",
        "title": "",
        "subTitle": "",
        "Api": "",
        "ApiParam": [],
        "value": "",
        "subValue": "",
        "dataType": "",
        "haschildren": false,
        "isTableView": false,
        "hasdatasource": false,
        "ResultDisplayField": [],
        "showchart": false,
        "chartOptions": {
          "chartType": "",
          "chartName": "",
          "theme": "light",
          "curveType": "Linear",
          "width": 100,
          "height": 50,
          "view": [
            100,
            50
          ]
        },
        "ResultApi": "",
        "ResultApiParam": []
      },
      {
        "key": "grid",
        "Name": "Advance Grid",
        "label": "Advance Grid",
        "icon": "fa fa-window-maximize",
        "type": "advancegrid",
        "width": 12,
        "showselectcolumn": true,
        "showeditlink": true,
        "showupdatelink": true,
        "showdeletelink": true,
        "showexportlink": true,
        "showemaillink": true,
        "showemanagecolumn": true,
        "showefreezecolumn": true,
        "primarykey": "",
        "editformid": "",
        "deleteapi": "",
        "deleteapiparam": [],
        "updateapi": "",
        "updateapiparam": [],
        "ResultApi": "",
        "emailformid": "",
        "emailfieldDestination": "",
        "emailfieldSource": "",
        "PagingType": "client",
        "PageSize": "10",
        "PageSizeParam": "",
        "ResultApiParam": [],
        "allowcardedit": false,
        "editcardredirecttype": "sidebar",
        "accessmodeforsidebar": "edit",
        "editcardurl": "",
        "paramforredirect": "",
        "ResultDisplayField": [],
        "rawquery": ""
      },
      {
        "key": "Attributes",
        "Name": "Progressbar",
        "icon": "fa fa-spinner",
        "type": "progressbar",
        "order": 1,
        "optionlist": [],
        "label": "",
        "width": null,
        "progressbartype": "",
        "barcolor": "",
        "striped": false,
        "animation": false,
        "outerstrokewidth": null,
        "outerstrokecolor": "",
        "outerstrokelinecap": "",
        "animationduration": null,
        "clockwise": false,
        "space": null,
        "showTitle": false,
        "titlecolor": "",
        "titlefontsize": "",
        "animatetitle": false,
        "showsubtitle": false,
        "subtitle": "",
        "subtitlecolor": "",
        "subtitlefontsize": "",
        "animatesubtitle": false,
        "showunits": false,
        "units": "",
        "unitsfontsize": "",
        "unitscolor": "",
        "showbackground": false,
        "backgroundstroke": "",
        "backgroundStrokeWidth": null,
        "backgroundPadding": null,
        "backgroundColor": "",
        "backgroundOpacity": null,
        "showInnerstroke": false,
        "innerstrokewidth": null,
        "innerstrokecolor": "",
        "tofixed": null,
        "renderonclick": false,
        "class": "",
        "barwidth": null,
        "barheight": null
      }
    ]
  }
  /* form API params control */
  export const FormApiParams = {
    "filtertype" : {
      "key": "filtertype",
      "Name": "Filter Type",
      "label": "Filter Type",
      "placeholder": "Filter Type",
      "showheader": false,
      "Panelheader": "",
      "icon": "fa fa-bars",
      "type": "checkboxlist",
      "direction": "verticle",
      "width": 6,
      "order": 11,
      "textfield": "key",
      "valuefield": "value",
      "Otherfield": "value",
      "require": false,
      "showinlist": false,
      "addinfilter": false,
      "filterheader": "",
      "haschildren": false,
      "hasdatasource": true,
      "isTableView": false,
      "allowother": false,
      "apiurl": "",
      "optionlist": [
        {
          "key": "Grid",
          "id": "8ae3927a-ce54-3b77-82be-5c8abce6fb39",
          "value": "Grid"
        },
        {
          "key": "List",
          "id": "de3f8103-6ab0-def4-68bd-3aeda110a199",
          "value": "List"
        },
        {
          "key": "Calender",
          "id": "de3f8123-6ab0-def4-68bd-3aeda110a199",
          "value": "Calender"
        },
        {
          "key": "KanBan",
          "id": "de3f8103-6df0-def4-68bd-3aeda110a199",
          "value": "KanBan"
        },
        {
          "key": "Map",
          "id": "de3f8203-6df0-def4-68bd-3aeda110a199",
          "value": "Map"
        },
        {
          "key": "Custom",
          "id": "de3f8343-6df0-def4-68bd-3aeda110a199",
          "value": "Custom"
        }
      ],
      "help": "",
      "helpdirection": "top"
    }
  }
